version: "3.8"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "8001:8000"
    volumes:
      - ./backend/app:/app
    env_file:
      - ./backend/.env
    restart: always
    depends_on:
      - chromadb

  chromadb:
    image: ghcr.io/chroma-core/chroma:latest
    container_name: chromadb
    ports:
      - "8000:8000"
    volumes:
      - ./backend/data/chromadb:/data/chromadb
    restart: always
