services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    working_dir: /app
    command: npm run dev -- --host 0.0.0.0
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: backend
    ports:
      - "8001:8000"
    volumes:
      - ./backend/app:/app
      - ./backend/data/chromadb:/data/chromadb
      - hf-cache:/root/.cache
    env_file:
      - ./backend/.env
    environment:
      CHROMADB_DIR: /data/chromadb
      MONGO_URI: mongodb://mongo:27017
    restart: always
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    depends_on:
      - mongo

  mongo:
    image: mongo:7
    container_name: mongo
    volumes:
      - ./backend/data/mongo:/data/db
    restart: always

volumes:
  hf-cache:
